### ISSUE TITLE
[Feature Request] Flipper-IRDB support?

### ISSUE THREAD

**Issue by Anarchtism** [regulad/SupIR#2]
Any chance [Flipper-IRDB](https://github.com/logickworkshop/Flipper-IRDB) could be supported? It has more remotes and is organized more nicely than irdb. Maybe even the ability to import any .ir file would be nice.

**Comment by regulad** [comment]
I took a glance at that repository, it’s really cool! Unfortunately, the
format seems significantly different than regular irdb and I would probably
have to rewrite my code-to-signal code to get it to work. However, a PR
adding this functionality is always welcome. I’ll leave this issue open in
case I have time to work on it or someone else opens a PR.

**Comment by regulad** [comment]
@Anarchtism this will be added in the next update!

**Comment by regulad** [comment]
Hi @Anarchtism & @notpushkin. I know this is a very stale issue for a project which hasn't received nor needed to receive any major updates in a few years, but I thought I would loop you in on my thought process.

I made this project back in secondary school, but I'm a computer/electrical engineering undergrad now! I have been preparing SupIR for inclusion in my engineering portfolio, and I thought it would be wise to revisit outstanding issues.

Flipper-IRDB was not included in the update in November 2024 because Flipper-IRDB did not then have a license that would allow it to be included as part of a synthesized/combined work. 

While Flipper-IRDB has since adopted a license that applies to new contributions, Flipper-IRDB includes [this bizzare disclaimer](https://github.com/Lucaslhm/Flipper-IRDB/blob/main/README.md?plain=1#L9) in their licensing stanza regarding past contributions  in the README.md which prevents me from naïvely including all of Flipper-IRDB in this project.

The approach Flipper-IRDB took towards adopting an open-source license is not only completely nonsensical but it makes the project difficult to work around, since I would have to look at the current version of each component file's blame and manually trim out pieces added before the license adoption. [Dolphin, a Wii/GC emulator, re-licensed itself about a decade ago. It had to contact every contributor who had contributed anything as small as a translation change before adopting GPL-2+](https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/) (Dolphin was already using GPL-2 and still had to do this!). I can only assume that the Flipper-IRDB maintainers were not aware of the legal ramifications of their actions and trudged through for the sake of "making something" rather than considering the consequences. _It is my opinion that maintainers of projects like this are partially responsible for the legally-apathetic reputations devices like the Flipper Zero have obtained._

[I have already had to jump through some mental loopholes](https://github.com/regulad/SupIR/blob/master/README.md?plain=1#L50) to make this project legally sound, so Flipper-IRDB will remain unimplemented.

**Comment by Anarchtism** [comment]
Oh, well. For what it's worth, [IR Blaster](https://github.com/iodn/android-ir-blaster) recently implemented the ability to import .ir files, letting it use any remote from Flipper-IRDB.

**Comment by regulad** [comment]
Importing external codes is out-of-scope for this app. The app you linked
appears to do a good job of that; for their project's longevity I left a
comment on an issue warning them of the legal ramifications of including a
dataset with the app. I primarily made this app as a "psuedo-embedded"
application; the linked app is going to be better for everyday use because
it is designed with that usecase in mind.
